- bower.json
- gulpfile.js
- package.json
- src/index.js
- tasks/copy.js
- tasks/default.js
Remove pixi.js as an NPM dependency to lock to a specific commit and not worry about NPM caching while v4 is still in development.
> Temporarily removed NPM Pixi dependency

- src/animate/Animator.js
- src/animate/MovieClip.js
Fixes #8.
Actions were being doubled up basically all the time, because they were getting performed when entering a frame and leaving it. 
Also stops actions from being doubled up when playing animations from Animator, by not calling both `gotoAndStop()` and `gotoAndPlay()`. As `goto...` performs actions, only `gotoAndStop()` is needed, as it is already on the correct frame when it is time to play.
> Fix actions getting performed when entering and leaving a frame.

- src/animate/Animator.js
- src/animate/AnimatorTimeline.js
- src/animate/MovieClip.js
* Adds `Animator.stopAll` to stop all the current animation timelines
* Adds `Animator.fromTo(instance, start, end, loop, callback)` as a lower-level version of `play` to allow for different types of label schemas or to use frame numbers.
* Adds `Animator.to(instance, end, callback)` to play to a certain frame and get a callback.
* Adds `Animator.play(instance, callback)` this will play the entire timeline from 0 to the last frame.
* Fixes an issue where Animator would go past the end frame when animating in low performing environments
> Animator Improvements

- src/animate/Animator.js
- src/animate/MovieClip.js
* Creates a public readOnly MovieClip property `labelsMap` for getting a dictionary of labels.
* Added readOnly static MovieClip property for the `DEFAULT_FRAMERATE` if no other framerate has been set (default is `24`, the Adobe Animate default)
* Resolves bug #13 by making ensuring a framerate is set.
> Fixes Playback Framerate Issues

- .travis.yml
- src/animate/load.js
- tasks/common/bundler.js
Fixes #17 by running the Babel es2015 preset in 'loose' mode.
Have tested in IE9 and can confirm that everything seems to work after this fix.
> IE9 support

- src/animate/MovieClip.js
- src/animate/index.js
- src/animate/load.js
- src/animate/sound.js
This adds the `playSound` method to `PIXI.animate.MovieClip` as discussed in the [pixi-animate-extension pr](https://github.com/jiborobot/pixi-animate-extension/pull/19).
I was working with these changes in my project for a couple days last week and I feel like it does the job pretty well.
> Create new sound emitter and playSound function

- src/mixins/DisplayObject.js
Currently the mask warning can indirectly break later `DisplayObject` references due to its return being `undefined`. This fix allows the object to be referenced in chaining and variable assignments even when the mask is not applied.
> Fix to setMask to retain object chaining on warning.

- src/animate/MovieClip.js
- src/animate/Tween.js
* Tween's `setPropFromShorthand` method skips the transform's getters.
* MovieClip has some regularly used methods saved on the instance to avoid going to the prototype for use.
> Slight optimizations to MovieClip and Tween.

- src/mixins/Text.js
This fixes text align being lost with compressed output.
For example in the value for 'center' is compressed to '0' which is coerced to 'left' on this line:
https://github.com/jiborobot/pixi-animate/blob/master/src/mixins/Text.js#L22
> Fix text align with compressed output js

- src/mixins/Text.js
Sorry @bigtimebuddy, just spotted a small problem with my last PR in that with non-compressed output align 'left' would be set to '2' for the anchoring, rather than the expected '-1'.
> Text align left should be set to -1

- README.md
- ambient.d.ts
- index.d.ts
- src/animate/load.js
Changed typings included via `require()` to be a module typing, kept previous file as global typing for optional inclusion in place of the module typing.
> Better module typing

- src/index.js
If pixi-animate is included multiple times, don't redefine PIXI.animate, just export the existing version.
> Don't redefine PIXI.animate.

- ambient.d.ts
- index.d.ts
Added an overload for Animator.play() to .d.ts files, for the `Animator.play(clip, callback)` form.
> Added an overload for Animator.play() to d.ts files

- ambient.d.ts
- index.d.ts
- src/animate/Scene.js
- src/animate/index.js
Creates a new Scene object which extends the brand new `PIXI.Application` API to create for much simpler setup code.
Requires unreleased version of PIXI: v4.3.3
> Add a new Scene API for easier construction

- src/animate/SymbolLoader.js
Fixes: https://github.com/jiborobot/pixi-animate/issues/48
> Calling next() if resource.data doesn't exist

- README.md
I noticed the url for the documentation site in the readme resulted in a 404 not found. This pr should update it with the real url
> Update documentation website link

- README.md
- index.d.ts
Updated index.d.ts to be consistent with the way pixi-sound exports its type definitions. This enables importing of pixi-animate type definitions via `/// <reference types="pixi-animate" />` rather than `/// <reference path="../node_modules/pixi-animate/ambient.d.ts" />` and also importing of the module code via `import 'pixi-animate';` rather than `import * as animate from 'pixi-animate';`
> Module typings fix

- src/animate/MovieClip.js
When changing FPS of a playing MovieClip, the current time value was being recalculated to be at the start of the current frame at the new FPS. This can cause a stutter because we're going back in time by a small amount. Multiple changes to FPS in less than 1/FPS seconds cause a hang in the animation.
This change updates the time more accurately as to actual progress through the animation, eliminating stutter/hang on FPS change.
> Smoother FPS changes

- src/animate/AnimatorTimeline.js
Addresses issue of overshooting the ending frame of an AnimatorTimeline on low-performing devices when the MovieClip's loop property is true and the end frame of the animation is also the last frame of the MovieClip's Timeline.
This isn't my favorite solution for this problem. I think the right way to deal with this would be to make the Animator or AnimatorTimeline responsible for advancing the MovieClip's Timeline, but that seems like it would be a relatively larger change, and I'm assuming there's a reason the Animator wasn't made that way in the first place.
>  Fix for overshooting end frame when FPS is low

- src/animate/MovieClip.js
To increase speed of all movieclips, better to use SharedTicker.speed instead of setting framerate for each movieclip.
> Remove SharedTicker.speed from tick function

- ambient.d.ts
- index.d.ts
PixiAnimate adds a setTint function to DisplayObject - overriding the typings on DisplayObject is tricky (or impossible), and the mixin strategy should be rethought for V2, but this change gets more accurate typings for MovieClip
> add typings for setTint function to MovieClip

- .travis.yml
- ambient.d.ts
- index.d.ts
- src/animate/load.js
Added flag to LoadOptions to prevent automatic instantiation of stage upon load complete. Instantiating an entire stage can be very expensive, and isn't always necessary.
> allow disabling automatic stage instantiation

- src/animate/Tween.ts
Makes skew tweening always go the short way. Previously a skew tween from 180° to -170° would traverse 350° when the default behavior in Animate would be a tween of 10°.
> Skew tweening fix

- src/animate/MovieClip.ts
If an instance has skew values modified at any point in the timeline, convert any rotation values to skew values at runtime, to allow for correct behavior when tweening between rotation and skew values. When publishing with [Animate Extension #91](https://github.com/pixijs/animate-extension/pull/91), this should only happen when intentionally using skew in Animate, but for some earlier published content, it is possible for skew and rotation to be intermixed on a timeline where only rotation was intended to be used.
> handle skew<->rotation tweens

- src/animate/MovieClip.ts
I found a couple mistakes with #125: 
SkewX was not being inverted when converted from rotation.
Some published frames have non-zero skew values and defined `0` rotation values, and the skew values were getting overridden with 0. Now, any already-set skew values take precedence rather than being overwritten by rotation.
> Correct skewX values, don't override set skew

- src/animate/Timeline.ts
- src/animate/Tween.ts
Fix issue with jumping to a non-keyframed frame following a tween. Makes sure there are Tween objects representing the full duration of a Timeline. 
Problem behavior was: when skipping more than 1 frame past a tween using gotoAndStop(), if no new static keyframes existed after the tween, properties would not update to their correct values.
> Fix gotoAndStop issue

- src/animate/load.ts
https://github.com/pixijs/animate/issues/142
> Added possibility to handle progress during load
